# Generated by Django 4.2.3 on 2023-07-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_options_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/productos'),
        ),
    ]
