# Generated by Django 4.2.5 on 2023-09-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_categoria_subcategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_producto', to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta_producto', to='productos.oferta'),
        ),
    ]
