# Generated by Django 4.2.5 on 2023-09-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_en_oferta_oferta_producto_oferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_original',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_con_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
