# Generated by Django 4.2.5 on 2023-09-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_rename_precio_producto_precio_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='oferta',
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
