# Generated by Django 4.2.5 on 2023-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_oferta_alter_producto_options_producto_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_con_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
