# Generated by Django 4.2.3 on 2023-09-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_plus_producto_en_plus_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/productos'),
        ),
    ]
