# Generated by Django 4.2.3 on 2023-09-12 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plus',
            name='porcentaje_descuento',
        ),
        migrations.AddField(
            model_name='plus',
            name='oferta_relacionada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.oferta'),
            preserve_default=False,
        ),
    ]
