# Generated by Django 4.2.3 on 2023-09-12 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_remove_plus_porcentaje_descuento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plus',
            old_name='fecha_fin',
            new_name='fecha_finalizacion',
        ),
        migrations.AddField(
            model_name='plus',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plus',
            name='producto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='plus_producto', to='productos.producto'),
            preserve_default=False,
        ),
    ]
