# Generated by Django 4.2.5 on 2023-09-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_rename_fecha_fin_plus_fecha_finalizacion_plus_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_con_descuento_plus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
